# Generated by Django 5.1.5 on 2025-02-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcommentmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'blog comment', 'verbose_name_plural': 'blog comments'},
        ),
    ]
