# Generated by Django 5.1.5 on 2025-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newscategorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last_name')),
            ],
            options={
                'verbose_name': 'news author',
                'verbose_name_plural': 'news authors',
            },
        ),
        migrations.CreateModel(
            name='NewsTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='categories',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='authors',
            field=models.ManyToManyField(related_name='news', to='app_news.newsauthormodel'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='app_news.newstagmodel'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='categories',
            field=models.ManyToManyField(related_name='news', to='app_news.newscategorymodel'),
        ),
    ]
