# Generated by Django 5.1.5 on 2025-02-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_newsauthormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscommentmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
