# Generated by Django 5.1.5 on 2025-01-30 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0002_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
